#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Verifying commit message is valid"
 npx --no-install commitlint --edit "$1"


echo "Linting only staged files from .husky/pre-commit"

npx lint-staged